name: Preproduccion

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
    - run: npm run start
    - run: echo "Ejecutando pruebas Unitarias..."
    - run: echo "Pruebas exitosas"
